apiVersion: v1
kind: Secret
metadata:
  name: rustbucket-secrets
  namespace: rustbucket
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg2://USER:PASSWORD@HOST/DATABASE"
  GITHUB_TOKEN: "REPLACE_WITH_GITHUB_TOKEN"