"""initial tables

Revision ID: aca6f36c7738
Revises: 9439e06098f8
Create Date: 2026-09-20 12:18:17.021617

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'aca6f36c7738'
down_revision: str | Sequence[str] | None = '9439e06098f8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
